meta_product_name: “Léo Bufi - Developer & Webdesigner”

meta_title: “Léo Bufi - Developer & Webdesigner”

meta_description: “Hi ! I’m Léo Bufi, a freelance developper & web designer based in Marseille. I like to make useful, solid and usable projects.”
